### ISSUE TITLE
Wrong fps count 

### ISSUE THREAD

**Issue by andrewgreenh** [DAB0mB/radial-snake#1]
Hello, found this project in reddit. 

One logic error I spotted is in game js. In the loop function you are using setTimeout(fn, fps)  but fps is 60 so your loop will not run every 16 ms for 60fps) but every 60 ms (17fps)

**Comment by DAB0mB** [comment]
@andreasgruenh Thank you for submitting this issue! Indeed the refresh rate was not calculated correctly, and I patched it over here: https://github.com/DAB0mB/radial-snake/commit/489b6791f4d84569cb4a3c7799d53d91df528ac2#diff-ffadca4f8ebdae8ae4da9f6cc17b62d3R14

**Comment by andrewgreenh** [comment]
You should use the fps property in your refresh rate property :P or remove the fps property.

**Comment by DAB0mB** [comment]
Yes I just changed it :-)
